services:
  db:
    image: postgres:17.0-alpine3.20
    restart: unless-stopped
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - 5432
    env_file:
      - ./.env
  web:
    build: .
    restart: unless-stopped
    volumes:
      - ".:/app"
    ports:
      - "${HTTP_PORT}:80"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data: